extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:30080"

processors:
  batch:
  queued_retry:

exporters:
  jaeger:
    endpoint: jaeger-all-in-one:14250
    insecure: true
  logging:
    loglevel: debug

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, queued_retry]
      exporters: [jaeger, logging]
